In [1]:
## Numpy

In [4]:
import numpy as np

In [5]:
list_to_convert = [1,2,3] #new
numpy_array=np.array(list_to_convert)
numpy_array #new

array([1, 2, 3])

In [6]:
a = [1,2,3,4,5] # corrected
a_numpy = np.array(a)
a_numpy.shape #new

(5,)

In [8]:
row_vector = a_numpy[:,np.newaxis]
row_vector.shape #new

(5, 1)

In [10]:
col_vector = a_numpy[np.newaxis, :]
col_vector.shape #new

(1, 5)

In [11]:
a = range(0,15) #list of numbers from 0 to 14
a_numpy = np.array(a) #new 
b = a_numpy.reshape(3,5)  
b #corrected 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a = [(1,2), [3,4,(5)], (6,7,8)]
b = np.asarray(a)
b #corrected 

array([(1, 2), list([3, 4, 5]), (6, 7, 8)], dtype=object)

In [14]:
#code removed 
a = np.zeros((3,4), dtype = np.float16)
a #new 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

In [15]:
a = np.ones((3,4), dtype=np.int32)
a #new 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
#code below put in a comment
#np.full(shape_as_tuple, value_to_fill, dtype=type_you_want) 
a = np.full((2,3), 1, dtype=np.float16)
a #new 

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [18]:
#new cell 
#code below put in a comment
#np.empty(shape_as_tuple,dtype=int) 
a = np.empty((2,2),dtype=np.int16)
a #new 

array([[    0,     0],
       [    0, 16368]], dtype=int16)

In [19]:
#code below put in a comment
#np.linspace(start,stop,num=int_value,endpoint=bool_value,retstep=bool_value)
np.linspace(1,2,num=5,endpoint=False,retstep=True)

(array([1. , 1.2, 1.4, 1.6, 1.8]), 0.2)

In [20]:
#code below put in a comment 
#np.arange(start=where_to_start,stop=where_to_stop,step=step_size)
np.arange(1, 10, 2) # new

array([1, 3, 5, 7, 9])

In [21]:
print(a) #new
a.shape #corrected

[[    0     0]
 [    0 16368]]


(2, 2)

In [22]:
x = np.array([1,2,3])
x.ndim #corrected

1

In [23]:
x = np.ones((3,2,4),dtype=np.int16)
print(x) #new 
x.size #corrected

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


24

In [24]:
#code below put in a comment 
#24 * bytes occupied by 16 bit integer = 24 * 2 = 48
x.nbytes

48

In [25]:
x = np.ones((2,3), dtype=np.int16)
x.dtype #corrected 
#code here is now the text below

dtype('int16')

In [26]:
y = np.array([[1,3],[5,6]])
y #new 

array([[1, 3],
       [5, 6]])

In [27]:
#new cell 
x = np.copy(y)
x #new 

array([[1, 3],
       [5, 6]])

In [28]:
#new cell 
x[0, 0] = 1000 #corrected
x #corrected 

array([[1000,    3],
       [   5,    6]])

In [29]:
y #corrected

array([[1, 3],
       [5, 6]])

In [30]:
x = np.array([[1,2],[3,4]]) #corrected
x #corrected 

array([[1, 2],
       [3, 4]])

In [31]:
#new cell
x.T #corrected

array([[1, 3],
       [2, 4]])

In [32]:
#code removed 
x.reshape(-1) #corrected 

array([1, 2, 3, 4])

In [33]:
#code removed 
x.ravel() #corected

array([1, 2, 3, 4])

In [34]:
x = np.ones((3,4,5))
x #new 

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [35]:
#new cell
#code below put in a comment 
#np.moveaxis(x,axes_to_move_as_list, destination_axes_as_list)
np.moveaxis(x, [1,2], [0,-2]) # corrected 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [36]:
x #new 

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [38]:
x = np.array([[1,2],[3,4]])
x.shape  #corrected 
print(x) #corrected 

[[1 2]
 [3 4]]


In [39]:
#new cell
np.swapaxes(x,0,1)

array([[1, 3],
       [2, 4]])

In [40]:
x = np.ones((3,4,5)) #corrected 
print(x) #new 
x.shape  #corrected 

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(3, 4, 5)

In [41]:
#new cell 
y = np.swapaxes(x,0,2)
print(y)
y.shape

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


(5, 4, 3)

In [42]:
x = np.array([[3,4,5,9],[2,6,8,0]])
y = x.tolist()
print(y) #new
type(y) #corrected

[[3, 4, 5, 9], [2, 6, 8, 0]]


list

In [43]:
x = np.array([0,1,2.0,3.0,4.2],dtype=np.float32)
x #new 

array([0. , 1. , 2. , 3. , 4.2], dtype=float32)

In [44]:
#new cell
x.astype(np.int16) # corrected

array([0, 1, 2, 3, 4], dtype=int16)

In [49]:
#new cell 
x.astype(bool) #corrected

array([False,  True,  True,  True,  True])

In [50]:
x = np.array([0,1,2.0,3.0,4.2],dtype=np.float32)
x.nonzero() #corrected

(array([1, 2, 3, 4], dtype=int64),)

In [51]:
#new cell
x = np.array([[0,1],[3,5]])
x.nonzero()

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))

In [52]:
#comment below added as a comment
#np.ndarray.sort(axis=axis_you_want_to_sort_by)
x = np.array([[4,3],[3,2]]) # corrected
x

array([[4, 3],
       [3, 2]])

In [53]:
#new cell
x.sort(axis=1) #sort each row
#code removed
x #new 

array([[3, 4],
       [2, 3]])

In [54]:
#new cell 
x.sort(axis=0) #sort each col
#code removed 
x #new 

array([[2, 3],
       [3, 4]])

In [55]:
x = np.array([[0,1],[2,3]])
x == 1 #corrected

array([[False,  True],
       [False, False]])

In [56]:
(x == 1).astype(np.int16).sum()

1

In [57]:
a = np.eye(2) #identity matrix of size 2
a
#code removed 

array([[1., 0.],
       [0., 1.]])

In [58]:
#new cell 

b = np.array([[1,2],[3,4]])
b
#code removed

array([[1, 2],
       [3, 4]])

In [59]:
np.matmul(a,b) #corrected

array([[1., 2.],
       [3., 4.]])

In [60]:
np.multiply(a,b)

array([[1., 0.],
       [0., 4.]])

In [61]:
#comment added below
#np.dot(matrix1, matrix2)
a = np.array([[1,2,3],[4,8,16]])
a #corrected

array([[ 1,  2,  3],
       [ 4,  8, 16]])

In [62]:
b = np.array([5,6,11]).reshape(-1,1)
b #corrected

array([[ 5],
       [ 6],
       [11]])

In [63]:
np.dot(a,b) #corrected

array([[ 50],
       [244]])

In [64]:
a = np.array([[1, 2, 3, 4]]) #corrected
a #new 

array([[1, 2, 3, 4]])

In [65]:
#new cell 

b = np.array([4,5,6,7]).reshape(-1,1)
b #corrected

array([[4],
       [5],
       [6],
       [7]])

In [66]:
np.dot(a,b) #corrected 

array([[60]])

In [67]:
x = [1,2,3]
y = [4,5,6]
z = np.cross(x, y)
z #corrected

array([-3,  6, -3])

In [68]:
x = np.array([5, 10, 14, 17, 19, 26], dtype=np.float16)
np.gradient(x) #corrected 

array([5. , 4.5, 3.5, 2.5, 4.5, 7. ], dtype=float16)

In [69]:
#entire cell rewritten, new cells added 
x = np.array([[2,4,9],[3,1,5],[7,8,0]]) #new
x #new

array([[2, 4, 9],
       [3, 1, 5],
       [7, 8, 0]])

In [70]:
#new cell
#For a single element use:
#x[r,c], where r,c are row and col number of the element.
x[1,2] #new 

5

In [71]:
#new cell 
#For multiple, non-contiguous elements use:
#x[list_of_rows,list_of_cols]
x[[0,0,2,2],[0,1,0,1]] #corrected

array([2, 4, 7, 8])

In [72]:
#new cell 
#If one of the rows or cols are continuous, 
#it's easier to use a range of indices: 
x[[0,2],0:2] #corrected 

array([[2, 4],
       [7, 8]])

In [73]:
a = np.array([[3,5,8],[4,5,6],[9,7,2]]) #corrected
a #new

array([[3, 5, 8],
       [4, 5, 6],
       [9, 7, 2]])

In [74]:
#new cell
b = np.array([2,3,4]) #corrected
b #new

array([2, 3, 4])

In [75]:
#new cell
a.shape

(3, 3)

In [76]:
#new cell
b.shape

(3,)

In [77]:
#new cell 
np.array([[2,3,4], [2,3,4], [2,3,4]])

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [78]:
#new cell
a + b #corrected 

array([[ 5,  8, 12],
       [ 6,  8, 10],
       [11, 10,  6]])

In [2]:
## Pandas

In [3]:
import pandas as pd
import numpy as np

In [4]:
#df = pd.read_csv(file_path, sep=’,’, header = 0, index_col=False,names=None)

In [6]:
df_1 = pd.read_csv("imdb_ratings.csv")
# relabel index to start at 1 
df_1 = df_1.reindex(index=np.arange(1, df_1.shape[0], 1))
df_1.head()

Votes  Rank                       Title  Year  Decade
1  132823   8.3  Singin' in the Rain (1952)  1952    1950
2   74178   8.3        All About Eve (1950)  1950    1950
3  635139   8.6                 Léon (1994)  1994    1990
4  145514   8.2     The Elephant Man (1980)  1980    1980
5  425461   8.3    Full Metal Jacket (1987)  1987    1980

In [7]:
#where c1, c2, and c3 are lists
#dic = {'first_col_name':c1,'second_col_names':c2,'3rd_col_name':c3} 
#df = pd.DataFrame(data=d_dic)

In [8]:
dic_1= {'states': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
         'year': [2000, 2001, 2002, 2001, 2002, 2003],
         'pop': [1.5, .17, 3.6, 2.4, 2.9, 3.2]} 
dic_1

{'states': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 0.17, 3.6, 2.4, 2.9, 3.2]}

In [9]:
df_2=pd.DataFrame(data=dic_1)
df_2

states  year   pop
0    Ohio  2000  1.50
1    Ohio  2001  0.17
2    Ohio  2002  3.60
3  Nevada  2001  2.40
4  Nevada  2002  2.90
5  Nevada  2003  3.20

In [10]:
#np_data = any NumPy array
#df = pd.DataFrame(data=np_data, columns=list_of_Col_names)

In [11]:
np_data_1=np.array([[6, 7.5, 8], [0, 1, 2.0], [4, 2, 6]])
np_data_1

array([[6. , 7.5, 8. ],
       [0. , 1. , 2. ],
       [4. , 2. , 6. ]])

In [12]:
col_names=['Joe', 'Ben', 'Ann']

In [13]:
df_3=pd.DataFrame(data=np_data_1, columns=col_names)
df_3

Joe  Ben  Ann
0  6.0  7.5  8.0
1  0.0  1.0  2.0
2  4.0  2.0  6.0

In [14]:
df_1.head() #by default, displays first 5 rows 

Votes  Rank                       Title  Year  Decade
1  132823   8.3  Singin' in the Rain (1952)  1952    1950
2   74178   8.3        All About Eve (1950)  1950    1950
3  635139   8.6                 Léon (1994)  1994    1990
4  145514   8.2     The Elephant Man (1980)  1980    1980
5  425461   8.3    Full Metal Jacket (1987)  1987    1980

In [15]:
df_1.head(10)#top 10 

Votes  Rank                         Title  Year  Decade
1   132823   8.3    Singin' in the Rain (1952)  1952    1950
2    74178   8.3          All About Eve (1950)  1950    1950
3   635139   8.6                   Léon (1994)  1994    1990
4   145514   8.2       The Elephant Man (1980)  1980    1980
5   425461   8.3      Full Metal Jacket (1987)  1987    1980
6   441174   8.1              Gone Girl (2014)  2014    2010
7   850601   8.3          Batman Begins (2005)  2005    2000
8    37664   8.2  Judgment at Nuremberg (1961)  1961    1960
9    46987   8.0       Relatos salvajes (2014)  2014    2010
10   56842   8.1  It Happened One Night (1934)  1934    1930

In [16]:
df_1.tail(10)#bottom 10

Votes  Rank                                         Title  Year  Decade
240   117590   8.4                     The Great Dictator (1940)  1940    1940
241    85012   8.1                   Strangers on a Train (1951)  1951    1950
242   476501   8.6                         Cidade de Deus (2002)  2002    2000
243   268905   8.4                           Citizen Kane (1941)  1941    1940
244    69988   8.1                                     8½ (1963)  1963    1960
245  1078416   8.7                           Forrest Gump (1994)  1994    1990
246    31003   8.1                  Le salaire de la peur (1953)  1953    1950
247   167076   8.2                               3 Idiots (2009)  2009    2000
248    91689   8.1                                Network (1976)  1976    1970
249   589477   8.3  Eternal Sunshine of the Spotless Mind (2004)  2004    2000

In [17]:
#col = list_of_columns_to_view 
#df[col].head(num_of_rows_to_view)
cols_1 = ['Rank', 'Title']
df_1[cols_1].head(10)

Rank                         Title
1    8.3    Singin' in the Rain (1952)
2    8.3          All About Eve (1950)
3    8.6                   Léon (1994)
4    8.2       The Elephant Man (1980)
5    8.3      Full Metal Jacket (1987)
6    8.1              Gone Girl (2014)
7    8.3          Batman Begins (2005)
8    8.2  Judgment at Nuremberg (1961)
9    8.0       Relatos salvajes (2014)
10   8.1  It Happened One Night (1934)

In [18]:
df_1[cols_1].tail(10)

Rank                                         Title
240   8.4                     The Great Dictator (1940)
241   8.1                   Strangers on a Train (1951)
242   8.6                         Cidade de Deus (2002)
243   8.4                           Citizen Kane (1941)
244   8.1                                     8½ (1963)
245   8.7                           Forrest Gump (1994)
246   8.1                  Le salaire de la peur (1953)
247   8.2                               3 Idiots (2009)
248   8.1                                Network (1976)
249   8.3  Eternal Sunshine of the Spotless Mind (2004)

In [19]:
#to save results, need to assign to new DataFrame 
new_df_1 = df_1.rename(columns={'Votes':'Total Votes','Title':'Movie Title'})
new_df_1.head()

Total Votes  Rank                 Movie Title  Year  Decade
1       132823   8.3  Singin' in the Rain (1952)  1952    1950
2        74178   8.3        All About Eve (1950)  1950    1950
3       635139   8.6                 Léon (1994)  1994    1990
4       145514   8.2     The Elephant Man (1980)  1980    1980
5       425461   8.3    Full Metal Jacket (1987)  1987    1980

In [20]:
#without tolist method, returns Indexed object
df_1.columns.tolist()

['Votes', 'Rank', 'Title', 'Year', 'Decade']

In [21]:
df_1['Rank'].value_counts() #returns key, frequency pair

8.1    53
8.0    50
8.3    38
8.2    34
8.5    24
8.4    21
8.6     9
8.7     9
8.9     6
9.2     2
8.8     2
9.0     1
Name: Rank, dtype: int64

In [22]:
df_1['Decade'].value_counts()[1940] #returns frequency of a key value

14

In [23]:
new_df_1 = df_1.reset_index(drop=True,inplace=False) #revert back to original indexing
new_df_1.head()

Votes  Rank                       Title  Year  Decade
0  132823   8.3  Singin' in the Rain (1952)  1952    1950
1   74178   8.3        All About Eve (1950)  1950    1950
2  635139   8.6                 Léon (1994)  1994    1990
3  145514   8.2     The Elephant Man (1980)  1980    1980
4  425461   8.3    Full Metal Jacket (1987)  1987    1980

In [24]:
new_df_1 = df_1.drop(columns = ['Votes', 'Decade']) #not done in place
new_df_1.head()

Rank                       Title  Year
1   8.3  Singin' in the Rain (1952)  1952
2   8.3        All About Eve (1950)  1950
3   8.6                 Léon (1994)  1994
4   8.2     The Elephant Man (1980)  1980
5   8.3    Full Metal Jacket (1987)  1987

In [25]:
new_df_1.set_index('Rank',inplace=True) #sets Rank as new index 
new_df_1.head()

Title  Year
Rank                                  
8.3   Singin' in the Rain (1952)  1952
8.3         All About Eve (1950)  1950
8.6                  Léon (1994)  1994
8.2      The Elephant Man (1980)  1980
8.3     Full Metal Jacket (1987)  1987

In [26]:
new_df_1 = df_1.reindex(index=np.arange(1, 255, 1)) #reindex with more rows 
new_df_1.tail(10) #new rows have missing values 

Votes  Rank                                         Title    Year  \
245  1078416.0   8.7                           Forrest Gump (1994)  1994.0   
246    31003.0   8.1                  Le salaire de la peur (1953)  1953.0   
247   167076.0   8.2                               3 Idiots (2009)  2009.0   
248    91689.0   8.1                                Network (1976)  1976.0   
249   589477.0   8.3  Eternal Sunshine of the Spotless Mind (2004)  2004.0   
250        NaN   NaN                                           NaN     NaN   
251        NaN   NaN                                           NaN     NaN   
252        NaN   NaN                                           NaN     NaN   
253        NaN   NaN                                           NaN     NaN   
254        NaN   NaN                                           NaN     NaN   

     Decade  
245  1990.0  
246  1950.0  
247  2000.0  
248  1970.0  
249  2000.0  
250     NaN  
251     NaN  
252     NaN  
253     NaN  
254     NaN

In [27]:
new_df_1.dropna(axis=0,inplace=True)
new_df_1.tail(10)

Votes  Rank                                         Title    Year  \
240   117590.0   8.4                     The Great Dictator (1940)  1940.0   
241    85012.0   8.1                   Strangers on a Train (1951)  1951.0   
242   476501.0   8.6                         Cidade de Deus (2002)  2002.0   
243   268905.0   8.4                           Citizen Kane (1941)  1941.0   
244    69988.0   8.1                                     8½ (1963)  1963.0   
245  1078416.0   8.7                           Forrest Gump (1994)  1994.0   
246    31003.0   8.1                  Le salaire de la peur (1953)  1953.0   
247   167076.0   8.2                               3 Idiots (2009)  2009.0   
248    91689.0   8.1                                Network (1976)  1976.0   
249   589477.0   8.3  Eternal Sunshine of the Spotless Mind (2004)  2004.0   

     Decade  
240  1940.0  
241  1950.0  
242  2000.0  
243  1940.0  
244  1960.0  
245  1990.0  
246  1950.0  
247  2000.0  
248  1970.0  
249  2000.0

In [28]:
mask_1 = (df_1['Decade'] == 1950) 
#or 
mask_2 = df_1['Decade'].isin([1950, 1960])
movies_1950s = df_1[mask_1]
movies_1950s.head()

Votes  Rank                       Title  Year  Decade
1   132823   8.3  Singin' in the Rain (1952)  1952    1950
2    74178   8.3        All About Eve (1950)  1950    1950
12  156432   8.3     Some Like It Hot (1959)  1959    1950
35   56671   8.0          The Killing (1956)  1956    1950
51   87437   8.0        Roman Holiday (1953)  1953    1950

In [29]:
movies_50_60s = df_1[mask_2]
movies_50_60s.head()

Votes  Rank                                      Title  Year  Decade
1   132823   8.3                 Singin' in the Rain (1952)  1952    1950
2    74178   8.3                       All About Eve (1950)  1950    1950
8    37664   8.2               Judgment at Nuremberg (1961)  1961    1960
12  156432   8.3                    Some Like It Hot (1959)  1959    1950
18  134552   8.1  Butch Cassidy and the Sundance Kid (1969)  1969    1960

In [30]:
mask_3 = (mask_1 & (df_1['Rank'] >= 8.5))
best_movies_1950s = df_1[mask_3]
best_movies_1950s

Votes  Rank                        Title  Year  Decade
86   123879   8.5          Sunset Blvd. (1950)  1950    1950
98   206216   8.7  Shichinin no samurai (1954)  1954    1950
105  384187   8.9          12 Angry Men (1957)  1957    1950
217  280432   8.5           Rear Window (1954)  1954    1950

In [31]:
df_1.head()

Votes  Rank                       Title  Year  Decade
1  132823   8.3  Singin' in the Rain (1952)  1952    1950
2   74178   8.3        All About Eve (1950)  1950    1950
3  635139   8.6                 Léon (1994)  1994    1990
4  145514   8.2     The Elephant Man (1980)  1980    1980
5  425461   8.3    Full Metal Jacket (1987)  1987    1980

In [32]:
#row 1,column 2 
df_1.iat[1, 2]

'All About Eve (1950)'

In [33]:
df_1.at[4, 'Title']

'The Elephant Man (1980)'

In [34]:
#titles of movies at indices 1, 3, 5
df_1.loc[[1,3,5], ['Rank', 'Title']] 

Rank                       Title
1   8.3  Singin' in the Rain (1952)
3   8.6                 Léon (1994)
5   8.3    Full Metal Jacket (1987)

In [35]:
#indices 1, 3 /columns 2, 3
df_1.iloc[[1,3],[2,3]]

Title  Year
2     All About Eve (1950)  1950
4  The Elephant Man (1980)  1980

In [36]:
total_votes = 0
for i,row in df_1.iterrows():
    total_votes += row['Votes']
formatted_total = "{:,}".format(total_votes)
print(formatted_total)  

86,178,431


In [37]:
rank_totals = 0 
for row in df_1.itertuples():
    rank_totals += row.Rank
avg_rank = rank_totals / df_1.shape[0]  # total / number of rows
print("Average rank is ", round(avg_rank, 2))

Average rank is  8.27


In [38]:
#by default, not in place
df_1.sort_values(by=['Year', 'Rank'], ascending=True).head(10) 

Votes  Rank                                Title  Year  Decade
173   55784   8.3                       The Kid (1921)  1921    1920
205   58506   8.2                 The Gold Rush (1925)  1925    1920
146   46332   8.2                   The General (1926)  1926    1920
49    98794   8.3                    Metropolis (1927)  1927    1920
216   92375   8.5                   City Lights (1931)  1931    1930
10    56842   8.1         It Happened One Night (1934)  1934    1930
212  121668   8.5                  Modern Times (1936)  1936    1930
101  259235   8.1              The Wizard of Oz (1939)  1939    1930
188  192791   8.1            Gone with the Wind (1939)  1939    1930
17    69510   8.2  Mr. Smith Goes to Washington (1939)  1939    1930

In [39]:
def reformat_votes(v):
    return v / 1000
df_1['Votes'].apply(reformat_votes).head()

1    132.823
2     74.178
3    635.139
4    145.514
5    425.461
Name: Votes, dtype: float64

In [40]:
def reformat_votes(v, size):
    return v / size
df_1['Votes'].apply(reformat_votes, size=100).head()

1    1328.23
2     741.78
3    6351.39
4    1455.14
5    4254.61
Name: Votes, dtype: float64

In [41]:
def votes_per_rank(row):
    return row['Votes'] / row['Rank']
df_1[['Votes', 'Rank']].apply(votes_per_rank, axis=1).head()

1    16002.771084
2     8937.108434
3    73853.372093
4    17745.609756
5    51260.361446
dtype: float64

In [42]:
df_3

Joe  Ben  Ann
0  6.0  7.5  8.0
1  0.0  1.0  2.0
2  4.0  2.0  6.0

In [43]:
def multiply_by_10(val):
    return val * 10
new_df_3 = df_3.applymap(multiply_by_10)
new_df_3

Joe   Ben   Ann
0  60.0  75.0  80.0
1   0.0  10.0  20.0
2  40.0  20.0  60.0

In [44]:
df_1[df_1['Year'].isin([1980, 1970, 1960])]

Votes  Rank                                              Title  Year  \
4    145514   8.2                            The Elephant Man (1980)  1980   
38   532559   8.4                                 The Shining (1980)  1980   
67    96190   8.3                               The Apartment (1960)  1960   
156  700283   8.7  Star Wars: Episode V - The Empire Strikes Back...  1980   
200  210647   8.2                                 Raging Bull (1980)  1980   
219  371791   8.5                                      Psycho (1960)  1960   

     Decade  
4      1980  
38     1980  
67     1960  
156    1980  
200    1980  
219    1960

In [45]:
df_1[~df_1['Decade'].isin([1950, 1960, 1970, 1930])].head()

Votes  Rank                     Title  Year  Decade
3  635139   8.6               Léon (1994)  1994    1990
4  145514   8.2   The Elephant Man (1980)  1980    1980
5  425461   8.3  Full Metal Jacket (1987)  1987    1980
6  441174   8.1          Gone Girl (2014)  2014    2010
7  850601   8.3      Batman Begins (2005)  2005    2000

In [46]:
df_1.groupby(['Decade']).agg({'Rank':'mean'})

Rank
Decade          
1920    8.250000
1930    8.250000
1940    8.257143
1950    8.233333
1960    8.231818
1970    8.309524
1980    8.241935
1990    8.357143
2000    8.260000
2010    8.200000

In [47]:
df_2

states  year   pop
0    Ohio  2000  1.50
1    Ohio  2001  0.17
2    Ohio  2002  3.60
3  Nevada  2001  2.40
4  Nevada  2002  2.90
5  Nevada  2003  3.20

In [48]:
new_df_2=df_2.groupby(['year']).agg(list)
new_df_2

states          pop
year                             
2000          [Ohio]        [1.5]
2001  [Ohio, Nevada]  [0.17, 2.4]
2002  [Ohio, Nevada]   [3.6, 2.9]
2003        [Nevada]        [3.2]

In [49]:
mask_4 = df_1['Year'].isin([1925, 1935, 1945, 1955, 1965])
movies_on_the_fives = df_1[mask_4]
movies_on_the_fives

Votes  Rank                              Title  Year  Decade
119   36725   8.1             Les diaboliques (1955)  1955    1950
153  135556   8.3  Per qualche dollaro in più (1965)  1965    1960
205   58506   8.2               The Gold Rush (1925)  1925    1920
237   57974   8.0     The Night of the Hunter (1955)  1955    1950

In [50]:
mask_5=(df_1['Rank'] == 8.8)
movies_8_8=df_1[mask_5]
movies_8_8

Votes  Rank                                              Title  Year  \
87   1177098   8.8                                  Fight Club (1999)  1999   
178  1099087   8.8  The Lord of the Rings: The Fellowship of the R...  2001   

     Decade  
87     1990  
178    2000

In [51]:
#vertical concatenation 
movies_on_fives_and_8_8 = pd.concat([movies_on_the_fives, movies_8_8], axis=0)
movies_on_fives_and_8_8

Votes  Rank                                              Title  Year  \
119    36725   8.1                             Les diaboliques (1955)  1955   
153   135556   8.3                  Per qualche dollaro in più (1965)  1965   
205    58506   8.2                               The Gold Rush (1925)  1925   
237    57974   8.0                     The Night of the Hunter (1955)  1955   
87   1177098   8.8                                  Fight Club (1999)  1999   
178  1099087   8.8  The Lord of the Rings: The Fellowship of the R...  2001   

     Decade  
119    1950  
153    1960  
205    1920  
237    1950  
87     1990  
178    2000

In [52]:
df_4=pd.DataFrame({'Tim': [85, 90, 76], 'Tom': [67, 45, 80], 'Jen': [99, 94, 87]}, index=(['Quiz 1', 'Quiz 2', 'Quiz 3']))

In [53]:
df_4

Tim  Tom  Jen
Quiz 1   85   67   99
Quiz 2   90   45   94
Quiz 3   76   80   87

In [54]:
df_5 = pd.DataFrame({'Rob': [57, 20, 67], 'Ken': [76, 54, 60], 'Amy': [90, 49, 78]}, index=(['Quiz 1', 'Quiz 2', 'Quiz 3']))

In [55]:
df_5

Rob  Ken  Amy
Quiz 1   57   76   90
Quiz 2   20   54   49
Quiz 3   67   60   78

In [56]:
#for horizontal concatenation 
combined_df= pd.concat([df_4, df_5], axis=1)
combined_df 

Tim  Tom  Jen  Rob  Ken  Amy
Quiz 1   85   67   99   57   76   90
Quiz 2   90   45   94   20   54   49
Quiz 3   76   80   87   67   60   78

In [57]:
df_6=pd.DataFrame({'Name': ['Ed', 'Flo', 'Jed'], 'Age': [76, 54, 60]})
df_6

Name  Age
0   Ed   76
1  Flo   54
2  Jed   60

In [58]:
df_7=pd.DataFrame({'Name': ['Ed', 'Flo', 'Jed'], 'Salary': [95000, 78000, 57000]})
df_7

Name  Salary
0   Ed   95000
1  Flo   78000
2  Jed   57000

In [59]:
df_6.merge(df_7, on=['Name'],how='inner')

Name  Age  Salary
0   Ed   76   95000
1  Flo   54   78000
2  Jed   60   57000

In [ ]:
#What are some useful things you can you do with numpy and pandas?

#Pandas is a library built upon numpy that allows the user to clean 
#and prepare data for analyzing. Data may be manipulated and organized 
#through the creation of dataframes, selection of elements, slicing/reshaping/combining 
#arrays, performing numerical operations, and grouping/merging/filtering by specifications. 
#These are just a few of the useful things that can be done with numpy and pandas.

In [ ]:
#Why would those useful things be helpful in data analysis?

#These applications of numpy and pandas are useful because 
#they allow data analysts to refine and manipulate data to fit 
#the needs of the analyst. The ability to clean and visualize large 
#datasets is critical. 

In [ ]:
#What challenges did you have in following the examples?

#I did not have any challenges with following the examples. However,
#I am sure I will run into difficulties as I implement these techniques 
#without guidance.